FROM aursu/rpmbuild:7-build

USER root
RUN yum -y install \
        gettext-devel \        
    && yum clean all && rm -rf /var/cache/yum

RUN yum -y --enablerepo=bintray-custom install \
        libtirpc-devel \
    && yum clean all && rm -rf /var/cache/yum
